# Generated by Django 6.1 on 2026-08-27 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=120)),
                ('contact_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('clothing_type', models.CharField(help_text="e.g. warm clothing, children's wear, work attire", max_length=120)),
                ('quantity', models.CharField(help_text="Approximate amount needed, e.g. '50 pieces'", max_length=80)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('event_created', 'Event created')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('donation_drive', 'Donation Drive'), ('thrift_swap', 'Thrift Swap'), ('other', 'Community Event')], max_length=20)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=140)),
                ('allow_participants', models.BooleanField(default=True, help_text='Members can sign up to take part (bring/swap clothes).', verbose_name='Allow participants')),
                ('allow_volunteers', models.BooleanField(default=True, help_text='Members can sign up to help sort, organise, and run the event.', verbose_name='Requesting volunteers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_from', models.ForeignKey(blank=True, help_text='The clothing request this event was created in response to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.clothingrequest')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EventSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('volunteer', 'Volunteer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(related_name='events', through='core.EventSignup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventsignup',
            constraint=models.UniqueConstraint(fields=('user', 'event', 'role'), name='unique_user_event_role'),
        ),
    ]
